spring:
  application:
    name: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin,1
    url: jdbc:mysql://127.0.0.1:3306/zyqtest?characterEncoding=utf-8&useSSL=false